apiVersion: v1
kind: Template
labels:
  app: redisexporter
  template: redisexporter-buildconfig-with-secret
metadata:
  annotations:
    description: Redis Exporter database - BuildConfig with Secret
      see https://github.com/Worteks/docker-redisexporter
    iconClass: icon-redis
    openshift.io/display-name: Redis Exporter
    tags: redisexporter
  name: redisexporter-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-${FRONTNAME}-${REDIS_EXPORTER_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Redis Exporter images
    labels:
      name: redisexporter-${FRONTNAME}-${REDIS_EXPORTER_REPOSITORY_REF}
    name: redisexporter-${FRONTNAME}-${REDIS_EXPORTER_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 300m
        memory: 768Mi
    source:
      contextDir: /
      git:
        uri: ${REDIS_EXPORTER_REPOSITORY_URL}
        ref: "${REDIS_EXPORTER_REPOSITORY_REF}"
      sourceSecret:
        name: git-${FRONTNAME}-${REDIS_EXPORTER_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: redisexporter-${FRONTNAME}:${REDIS_EXPORTER_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
- name: REDIS_EXPORTER_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: REDIS_EXPORTER_REPOSITORY_URL
  description: The URL of the repository with your redisexporter Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-redisexporter.git
